
export const EMPLOYEE_DETAILS_ACTION_TYPE = "EMPLOYEE_DETAILS_ACTION";
export const EMPLOYEE_STATUS_DETAILS_ACTION_TYPE = "EMPLOYEE_STATUS_DETAILS_ACTION";
export const EMPLOYEE_LATEST_DATE_ACTION_TYPE = "EMPLOYEE_LATEST_DATE_DETAILS_ACTION";